version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
      maintenance:
        applies-to: version-updates
        update-types: [minor, patch]
        patterns: ["*"]
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
      maintenance:
        applies-to: version-updates
        update-types: [minor, patch]
        patterns: ["*"]
