/* Journal observations, never inferred live agents or model identities. */
function studioPanel(root){
 const box=el('section',undefined,'studio');box.setAttribute('aria-label','Студия проекта');
 const head=el('div',undefined,'studio-head'),orb=el('div',undefined,'studio-orb');orb.setAttribute('aria-hidden','true');append(orb,el('span',undefined,'orbit ld ld-spin'),el('span','◈','ld ld-breath'));
 const intro=el('div');append(intro,el('div','AGENT TERMINAL / СТУДИЯ','eyebrow'),el('h2','История превращается в следующий шаг','studio-title'),el('p',state.mode==='snapshot'?'Сохранённый снимок · непрерывная связь с агентами не подключена':'Чтение журнала · непрерывная связь с агентами не подключена','studio-note'));append(head,orb,intro);box.append(head);
 const controls=el('div',undefined,'studio-controls'),pause=el('button',document.body.classList.contains('motion-paused')?'Включить движение':'Остановить движение');pause.setAttribute('aria-pressed',String(document.body.classList.contains('motion-paused')));pause.onclick=()=>{const stopped=document.body.classList.toggle('motion-paused');if(stopped)document.getAnimations().filter(a=>a.effect?.target===$('content')).forEach(a=>a.cancel());pause.textContent=stopped?'Включить движение':'Остановить движение';pause.setAttribute('aria-pressed',String(stopped))};controls.append(pause);
 const versions=el('button','Версии и снимки');versions.onclick=()=>chooseTab('releases');controls.append(versions);box.append(controls);
 box.append(el('p','Кольцо движется только при загрузке данных. Ниже — последние сохранённые запуски, а не список работающих сейчас моделей.','studio-note'));
 const grid=el('div',undefined,'studio-run-grid');const runs=arr(state.runs).slice().reverse().slice(0,3);
 const names={succeeded:'Команда завершилась',failed:'Команда завершилась с ошибкой',running:'Зарегистрирован запуск · активность неизвестна',starting:'Зарегистрирован старт',timed_out:'Превышено время',interrupted:'Прервано',launch_error:'Ошибка запуска',supervisor_error:'Ошибка контроля'};
 if(!runs.length)grid.append(el('p','Запуски пока не зарегистрированы. Модели и агенты не определены.','meta'));
 runs.forEach(r=>{const n=el('article',undefined,'studio-run');append(n,el('span',r.status==='succeeded'?'✓':r.status==='failed'?'!':'◇','studio-icon'),el('h3',r.task_id||r.run_id||'Запуск без имени'),badge(names[r.status]||'Состояние неизвестно',r.status==='succeeded'?'good':'warn'),el('p',r.model_id&&r.model_id!=='unknown'?'Модель (сообщена): '+r.model_id:'Модель не указана','meta'),el('p','Последнее событие: '+(r.ended_at||r.started_at||'дата неизвестна'),'meta'));const d=disclosure('studio:'+r.run_id,'Открыть свидетельство');d.append(el('pre',JSON.stringify({run_id:r.run_id,event_id:r.event_id,session_id:r.session_id,exit_code:r.exit_code,argv:r.argv},null,2),'code'));n.append(d);grid.append(n)});box.append(grid);root.append(box);
}
